"""add_recepcao_atendimentos

Revision ID: f61017de2d75
Revises: 0001
Create Date: 2026-05-23 21:38:08.357676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f61017de2d75'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepcao_atendimentos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.BigInteger(), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classificacao_risco', sa.Enum('VERMELHO', 'LARANJA', 'AMARELO', 'VERDE', 'AZUL', name='classificacao_risco_enum'), nullable=True),
    sa.Column('procedencia', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('historia_clinica', sa.Text(), nullable=True),
    sa.Column('hipotese_diagnostica', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_paciente_id',      'recepcao_atendimentos', ['paciente_id'],      unique=False)
    op.create_index('idx_rec_data_atendimento', 'recepcao_atendimentos', ['data_atendimento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rec_data_atendimento', table_name='recepcao_atendimentos')
    op.drop_index('idx_rec_paciente_id',      table_name='recepcao_atendimentos')
    op.drop_table('recepcao_atendimentos')
    # enum type criado junto com a tabela
    op.execute("DROP TYPE IF EXISTS classificacao_risco_enum")
    # ### end Alembic commands ###
