"""base: tabelas existentes em set/2026

Esquema do banco como estava em produção quando o Alembic entrou (24/09/2026).
O banco de produção foi só MARCADO nesta versão (alembic stamp 0001) -- esta
migração nunca rodou nele; serve pra montar um banco novo do zero.

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 03:00:30.927771-03:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bpa_lotes_backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook', sa.String(length=100), nullable=False),
    sa.Column('arquivo', sa.String(length=100), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('modificado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recebido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook', 'arquivo', name='uq_bpa_lote_notebook_arquivo')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cns', sa.String(length=15), nullable=True),
    sa.Column('num_cpf', sa.String(length=11), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('dtnasc', sa.String(length=8), nullable=True),
    sa.Column('sexo', sa.CHAR(length=1), nullable=True),
    sa.Column('raca', sa.String(length=2), nullable=True),
    sa.Column('maepcn', sa.String(length=100), nullable=True),
    sa.Column('logpcn', sa.String(length=100), nullable=True),
    sa.Column('numpcn', sa.String(length=100), nullable=True),
    sa.Column('bairro_pcnte', sa.String(length=100), nullable=True),
    sa.Column('ddtel_pcnte', sa.String(length=2), nullable=True),
    sa.Column('tel_pcnte', sa.String(length=9), nullable=True),
    sa.Column('ibge', sa.String(length=6), server_default='240360', nullable=False),
    sa.Column('ceppcn', sa.String(length=8), server_default='59575000', nullable=False),
    sa.Column('co_lograd', sa.String(length=3), server_default='081', nullable=False),
    sa.Column('nome_social', sa.String(length=100), nullable=True),
    sa.Column('idade', sa.String(length=50), nullable=True),
    sa.Column('civil', sa.String(length=50), nullable=True),
    sa.Column('ocupacao', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), server_default='010', nullable=False),
    sa.Column('naturalidade', sa.String(length=100), nullable=True),
    sa.Column('sem_documento', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cns'),
    sa.UniqueConstraint('num_cpf', name='pacientes_num_cpf_key')
    )
    op.create_index('idx_pac_cns', 'pacientes', ['cns'], unique=False)
    op.create_index('idx_pac_cpf', 'pacientes', ['num_cpf'], unique=False)
    op.create_index('idx_pac_nome', 'pacientes', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tentativas_falhas', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_username', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('recurso', sa.String(length=30), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('campos_alterados', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_auditoria_criado_em', 'logs_auditoria', ['criado_em'], unique=False)
    op.create_index('idx_logs_auditoria_recurso', 'logs_auditoria', ['recurso', 'recurso_id'], unique=False)
    op.create_table('recepcao_atendimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classificacao_risco', sa.Enum('VERMELHO', 'LARANJA', 'AMARELO', 'VERDE', 'AZUL', name='classificacao_risco_enum'), nullable=True),
    sa.Column('registro', sa.SmallInteger(), nullable=True),
    sa.Column('procedencia', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('historia_clinica', sa.Text(), nullable=True),
    sa.Column('hipotese_diagnostica', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_atd_data', 'recepcao_atendimentos', ['data_atendimento'], unique=False)
    op.create_index('idx_atd_pac', 'recepcao_atendimentos', ['paciente_id'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_criacao', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_sessoes_expira_em', 'sessoes', ['expira_em'], unique=False)
    # ### end Alembic commands ###

    # BPA dos notebooks: só lê pacientes/atendimentos e só grava a cópia dos
    # lotes. O usuário bpa_leitura é criado à mão (senha fora do git).
    op.execute("""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bpa_leitura') THEN
            GRANT SELECT ON pacientes, recepcao_atendimentos TO bpa_leitura;
            GRANT SELECT, INSERT, UPDATE ON bpa_lotes_backup TO bpa_leitura;
            GRANT USAGE ON SEQUENCE bpa_lotes_backup_id_seq TO bpa_leitura;
          END IF;
        END $$;
    """)


def downgrade() -> None:
    # Desfazer a base apaga TODAS as tabelas (pacientes, atendimentos...).
    raise RuntimeError("A migração base não se desfaz: apagaria o banco inteiro.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessoes_expira_em', table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index('idx_atd_pac', table_name='recepcao_atendimentos')
    op.drop_index('idx_atd_data', table_name='recepcao_atendimentos')
    op.drop_table('recepcao_atendimentos')
    op.drop_index('idx_logs_auditoria_recurso', table_name='logs_auditoria')
    op.drop_index('idx_logs_auditoria_criado_em', table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_table('usuarios')
    op.drop_index('idx_pac_nome', table_name='pacientes')
    op.drop_index('idx_pac_cpf', table_name='pacientes')
    op.drop_index('idx_pac_cns', table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('bpa_lotes_backup')
    # ### end Alembic commands ###
