"""atendimentos das planilhas manuais

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 16:49:27.914246-03:00
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos_planilha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_busca', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cns', sa.String(length=15), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('arquivo', sa.String(length=150), nullable=False),
    sa.Column('aba', sa.String(length=60), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=False),
    sa.Column('importado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_atp_cpf', 'atendimentos_planilha', ['cpf'], unique=False)
    op.create_index('idx_atp_data', 'atendimentos_planilha', ['data'], unique=False)
    op.create_index('idx_atp_nome_busca', 'atendimentos_planilha', ['nome_busca'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_atp_nome_busca', table_name='atendimentos_planilha')
    op.drop_index('idx_atp_data', table_name='atendimentos_planilha')
    op.drop_index('idx_atp_cpf', table_name='atendimentos_planilha')
    op.drop_table('atendimentos_planilha')
    # ### end Alembic commands ###
